# Generated by Django 2.0.1 on 2018-02-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollclasstime',
            name='group',
        ),
        migrations.AddField(
            model_name='enrollclasstime',
            name='group_id',
            field=models.IntegerField(default=0, verbose_name='group id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollclasstime',
            name='date',
            field=models.CharField(default='', max_length=10, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='enrollclasstime',
            name='end',
            field=models.CharField(default='', max_length=10, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='enrollclasstime',
            name='start',
            field=models.CharField(default='', max_length=10, verbose_name='start'),
        ),
    ]
