# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ahacredentials_enrollwarecredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahafield',
            name='type',
            field=models.CharField(choices=[('course', 'Course'), ('location', 'Location'), ('instructor', 'Instructor'), ('tc', 'Training Center'), ('ts', 'Training Site'), ('lang', 'Language')], default='', max_length=64, verbose_name='type'),
        ),
    ]
