# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180302_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollwaregroup',
            name='available_to_export',
            field=models.BooleanField(default=False, verbose_name='available to export'),
        ),
    ]
