# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180312_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahafield',
            name='type',
            field=models.CharField(choices=[('course', 'Course'), ('location', 'Location'), ('instructor', 'Instructor'), ('tc', 'Training Center'), ('ts', 'Training Site'), ('lang', 'Language'), ('class_description', 'Class description'), ('class_notes', 'Class notes')], default='', max_length=64, verbose_name='type'),
        ),
    ]
