# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180314_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHAGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=128, verbose_name='course')),
                ('location', models.CharField(default='', max_length=128, verbose_name='location')),
                ('instructor', models.CharField(default='', max_length=64, verbose_name='instructor')),
                ('training_center', models.CharField(default='', max_length=128, verbose_name='training center')),
                ('training_site', models.CharField(default='', max_length=128, verbose_name='training site')),
                ('roster_limit', models.IntegerField(default=0, verbose_name='max students')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='description')),
                ('notes', models.CharField(default='', max_length=1024, verbose_name='note')),
                ('enrollware_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aha_group', to='core.EnrollWareGroup')),
            ],
            options={
                'verbose_name_plural': 'aha groups',
                'verbose_name': 'aha group',
            },
        ),
    ]
