# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ahagroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahagroup',
            name='cutoff_date',
            field=models.CharField(default='', max_length=10, verbose_name='cutoff date'),
        ),
    ]
