# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_enrollwaregroup_sync_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollwaregroup',
            name='group_id',
            field=models.CharField(default='', max_length=10, verbose_name='group id'),
        ),
    ]
