# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180516_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollclasstime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='enrollclasstime',
            name='end',
        ),
        migrations.RemoveField(
            model_name='enrollclasstime',
            name='start',
        ),
        migrations.AddField(
            model_name='enrollclasstime',
            name='end_time',
            field=models.DateTimeField(default=None, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='enrollclasstime',
            name='start_time',
            field=models.DateTimeField(default=None, verbose_name='start date'),
        ),
    ]
