# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180521_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollClassTime',
        ),
        migrations.AddField(
            model_name='enrollwaregroup',
            name='end_time',
            field=models.DateTimeField(default=None, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='enrollwaregroup',
            name='start_time',
            field=models.DateTimeField(default=None, verbose_name='start date'),
        ),
    ]
