# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0002_user_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='version',
            field=models.CharField(choices=[('lite', 'Lite'), ('pro', 'Pro')], default='lite', help_text='Users with Lite plan could sync one class only', max_length=8, verbose_name='plan'),
        ),
    ]
